nailcare.

diff --git a/.github/workflows/dotnet-ci.yml b/.github/workflows/dotnet-ci.yml
--- a/.github/workflows/dotnet-ci.yml
+++ b/.github/workflows/dotnet-ci.yml
@@ -35,6 +35,10 @@ jobs:
         ports:
           - "1025:1025"
           - "1080:1080"
+      image-moq-server-nginx-kashilog:
+        image: ghcr.io/creatiovitae/image-moq-nginx-kashilog:2023-12.25
+        ports:
+          - "32123:80"
     steps:
     - uses: actions/checkout@v4
     - name: Setup .NET
@@ -55,6 +59,19 @@ jobs:
           sleep 5
           if [ $i -eq 5 ]; then
             echo "transaction-mail-server failed to respond after 5 retries"
+            exit 1
+          fi
+        done
+    - name: Ping image-moq-server-nginx-kashilog
+      run: |
+        for i in {1..5}; do
+          if curl --fail http://127.0.0.1:32123; then
+            break
+          fi
+          echo "image-moq-server-nginx-kashilog is not responding, retrying..."
+          sleep 5
+          if [ $i -eq 5 ]; then
+            echo "image-moq-server-nginx-kashilog failed to respond after 5 retries"
             exit 1
           fi
         done
